---
title: "gather_tweets"
author: "Adelaida Barrera"
date: "11/20/2020"
output: html_document
---

```{r, include = FALSE}

library(twitteR)
library(tidyverse)
library(rtweet)

# API authorization 
rtweet::create_token(app = "aletheia_hertie", 
                     consumer_key = "dUccFFYUBCdImYFvQeLVNV3ij",
                     access_secret = "g5Zpp9lmwPfdW5JB2l4srFu8Y1BGBeNvt3BkDjcUaJJrk",
                     access_token = "10536312-kRxNG26Yo9SWavI8ksHzOs1rhw9PGA90Kp5ioIelD",
                     consumer_secret = "RPLTQRvGix0sK6QKkNS0ZJq6y1lsc5nR5OGDahV77mydUYTplq")

```

```{r, echo=FALSE}

# Accounts most read by Cifras y Conceptos opinion leaders panel 
names <- c(
  "Daniel Samper",
  "Daniel Coronell", 
  "Gustavo Petro", 
  "Felix de Bedout",
  "Alvaro Uribe",
  "Vicky Davila", 
  "La Pulla",
  "Alejandro Gaviria",
  "Claudia Lopez",
  "Ivan Cepeda", 
  "Gustavo Bolivar",
  "Carolina Sanin", 
  "Ariel Avila",
  "Ivan Duque",
  "Manuel Rodriguez", 
  "Daniel Quintero", 
  "Jorgue Enrique Robledo",
  "Maria Jimena Duzan", 
  "Matador", 
  "Gustavo Gomez", 
  "Moises Wasserman", 
  "Catherine Juvinao") 

usernames <- c(
  "@DanielSamperO",
  "@DCoronell",
  "@petrogustavo",
  "@fdbedout",
  "@AlvaroUribeVel",
  "@VickyDavilaH",
  "@LaPullaOficial", 
  "@agaviriau",
  "@ClaudiaLopez", 
  "@IvanCepedaCast",
  "@GustavoBolivar", 
  "@SaninPazC", 
  "@ArielAnaliza",
  "@IvanDuque",
  "@manuel_rodb",
  "@QuinteroCalle", 
  "@JERobledo",
  "@MJDuzan",
  "@Matador000",
  "@gusgomez1701", 
  "@mwassermannl", 
  "@CathyJuvinao")
              
influencers <- data.frame()

for (i in usernames) {
  influencers <- rbind(influencers, 
                       twitteR::userTimeline(user = i, n = 3200, includeRts = TRUE) %>%
                         twListToDF())
  }

save(influencers, file = "data/tweets_influencers.RData")

```


```{r}

# Read list of accounts to scrape 
accounts_feminists <- read_csv("data/twitter_accounts_fem.csv")

# Gather last 3200 tweets from each account 
feminists <- rtweet::get_timeline(accounts_feminists$username, n = 3200)

# Modify feminists dataframe in order to do left_join with tweets df
accounts_feminists <- accounts_feminists %>% 
  rename(screen_name = username) %>% 
  mutate(screen_name = str_remove(screen_name, "@"))
  
# Add covariates included in initial list to tweets df 
feminists <- left_join(feminists, accounts_feminists, by = "screen_name")

save(feminists, file = "data/tweets_feminists.RData")

```

