---
title: "Network_analysis_individuals(words)"
output: html_document
---

# Network analysis

# In this section we are going to visualize text data as a weighted network. The goal is to count pairwise relative occurence of words.

```{r}
library(dplyr)
library(tidytext)
library(igraph)
library(tidyverse)
library(widyr)
library(glue)

# First, we want to count pairwise occurences of words which apperar together in the tweets: bigram count.

# Create bi-grams
fem_bigrams <- non_congress %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2)

fem_bigrams

# Exploring
fem_bigrams %>%
  count(bigram, sort = TRUE)

# Cleaning
bigrams_separated <- fem_bigrams %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% c(stopwords("spanish")),
         !word2 %in% c(stopwords("spanish")),
         !word1 %in% c("https"),
         !word2 %in% c("https"),
         !word1 %in% c("cada","vez","the","of", "mil", "gracias", "muchas"), 
         # pair of words frequent but not relevant
         !word2 %in% c("cada","vez","the","of", "mil","gracias", "muchas"), 
         ! is.na(word1),
         ! is.na(word2),
         !str_detect(word1, pattern = "[[:digit:]]"),
         !str_detect(word2, pattern = "[[:digit:]]"),
         !str_detect(word1, pattern = "[[:punct:]]"), 
         !str_detect(word2, pattern = "[[:punct:]]"),
         !str_detect(word1, pattern = "(.)\\1{2,}"),
         !str_detect(word2, pattern = "(.)\\1{2,}"),
         !str_detect(word1, pattern = "\\b(.)\\b"),
         !str_detect(word2, pattern = "\\b(.)\\b"))

# New bigrams count
fem_bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE) %>%
  rename(weight=n)

fem_bigram_counts
```


```{r}
# How to define a weighted network from a bigram count?

# Each word wis going to represent a node.
# Two words ae going to be connected if they appear as a bigram.
# The weight of an edge is the numer of times the bigram appears in the corpus.

threshold <- 100
# Initially we establish a 'big' threshold for visualization purposes

# Scale to visualize
scale_weight <- function(x, lambda) {
  x / lambda
}

network_ind <- fem_bigram_counts %>%
  filter(weight > threshold) %>%
  mutate(weight = scale_weight(x = weight, lambda = 2E3)) %>% 
  graph_from_data_frame(directed = FALSE)

network_ind

graph_bigram_network_ind <--plot(
  network_ind, 
  vertex.size = 0.5,
  vertex.label.color = 'black',
  vertex.label.cex = 0.5,
  vertex.label.dist = 0.5,
  edge.color = 'gray',
  main = 'Bigram Count Network Individual Accounts',
  sub = glue('Weight Threshold: {threshold}'),
  alpha = 50
)

graph_bigram_network_ind
```

```{r}
# We can add some additional information to the visualization: Set the sizes of the nodes and the edges by the degree and weight respectively.

# For a weighted network we can consider the weighted degree, which can be computed with the strength function.

V(network_ind)$degree <- strength(graph = network_ind)

# Compute the weight shares
E(network_ind)$width <- E(network_ind)$weight/max(E(network_ind)$weight)

graph_bigram_network_degree_ind <- plot(
  network_ind, 
  vertex.color = 'lightblue',
  vertex.size = 2*V(network_ind)$degree, # We scale the node size by degree
  vertex.label.color = 'black', 
  vertex.label.cex = 0.5, 
  vertex.label.dist = 0.5,
  edge.color = 'gray', 
  edge.width = 3*E(network_ind)$width ,
  # To set the edge width proportional to the weight relative value
  main = 'Bigram Count Network with weight degree 
  Individual Accounts', 
  sub = glue('Weight Threshold: {threshold}'), 
  alpha = 50
)

graph_bigram_network_degree_ind
```
```{r}
# We can extract the biggest connected component of the network as follows

# First, with the 'big' threshold

# Get connected components (clusters)
clusters(graph = network_ind)

# Select biggest connected component
V(network_ind)$cluster <- clusters(graph = network_ind)$membership

cc.network_ind <- induced_subgraph(
  graph = network_ind,
  vids = which(V(network_ind)$cluster == which.max(clusters(graph = network_ind)$csize))
)

cc.network_ind 

# We store the degree
V(cc.network_ind)$degree <- strength(graph = cc.network_ind)

# and compute the weight shares.
E(cc.network_ind)$width <- E(cc.network_ind)$weight/max(E(cc.network_ind)$weight)

graph_bigram_clusters_ind <- plot(cc.network_ind, 
  vertex.color = 'lightblue',
  vertex.size = 10*V(cc.network_ind)$degree,
  vertex.label.color = 'black', 
  vertex.label.cex = 0.6, 
  vertex.label.dist = 1.6,
  edge.color = 'gray', 
  edge.width = 3*E(cc.network_ind)$width ,
  main = 'Bigram Count Network (Biggest Connected Component)
  Individual Accounts', 
  sub = glue('Weight Threshold: {threshold}'), 
  alpha = 50)

graph_bigram_clusters_ind

# Second, we repeat the last steps with a smaller threshold. This will allow us to  get a more complex network.

threshold2 <- 50
# Initially we establish a 'big' threshold for visualization purposes

# Scale to visualize
scale_weight <- function(x, lambda) {
  x / lambda
}

network_ind2 <- fem_bigram_counts %>%
  filter(weight > threshold2) %>%
  mutate(weight = scale_weight(x = weight, lambda = 2E3)) %>% 
  graph_from_data_frame(directed = FALSE)

V(network_ind2)$degree <- strength(graph = network_ind2)
E(network_ind2)$width <- E(network_ind)$weight/max(E(network_ind2)$weight)


# Get connected components (clusters)
clusters(graph = network_ind2)

# Select biggest connected component
V(network_ind2)$cluster <- clusters(graph = network_ind2)$membership

cc.network_ind <- induced_subgraph(
  graph = network_ind2,
  vids = which(V(network_ind2)$cluster == which.max(clusters(graph = network_ind2)$csize))
)

cc.network_ind 

# We store the degree
V(cc.network_ind)$degree <- strength(graph = cc.network_ind)

# and compute the weight shares.
E(cc.network_ind)$width <- E(cc.network_ind)$weight/max(E(cc.network_ind)$weight)

graph_bigram_clusters_ind <- plot(cc.network_ind, 
  vertex.color = 'lightblue',
  vertex.size = 10*V(cc.network_ind)$degree,
  vertex.label.color = 'black', 
  vertex.label.cex = 0.6, 
  vertex.label.dist = 1.6,
  edge.color = 'gray', 
  edge.width = 3*E(cc.network_ind)$width ,
  main = 'Bigram Count Network (Biggest Connected Component)
  Individual Accounts', 
  sub = glue('Weight Threshold: {threshold2}'), 
  alpha = 50)

graph_bigram_clusters_ind
```

# Community detection
```{r}
# As Orduz (), we employ the Louvain Method for community detection, and to try to find clusters within the network. The precedent is an algorithm for detecting communities in networks. It evaluates how much more densely connected the nodes within a community are, compared to how connected they would be in a random network (neo4j, December 2020). It recursively merges communities into a single node and executes the modularity clustering on the condensed graphs.

comm_detection_ind<- cluster_louvain(
  graph = cc.network_ind, 
  weights = E(cc.network_ind)$weight
)

comm_detection_ind

# We see that 4 groups where identified and the modularity (measure for the “quality” of certain partition of the nodes in a network like clusterings) is 0.5. This result its either good or bad (better if closer to 1). However, the network that we identify here is considering all the top frequent bigrams (not clusters). The high modularity can be a consequence of the last. 

```


