---
title: "sentiment_analysis_institutions"
author: "Mariana Saldarriaga"
date: "12/20/2020"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
theme_set(theme_minimal())

library(quanteda)

# Dictionary 
sentimiento_d <- read.delim(file = "SpanishSentimentLexicons/fullStrengthLexicon.txt",
                          header = F,
                          col.names = c("word", "code", "sentiment", "score2"))

sentimiento_dict <- as.dictionary(sentimiento_d)
sentimiento_dict

# Dfm with dictionary by main occupation
sentimiento_dfm_inst <- dfm(institutions_corp,
                            groups = c("screen_name"),
                            dictionary = sentimiento_dict)

sentimiento_df_inst <- convert(sentimiento_dfm_inst, "data.frame") %>%
  gather(neg, pos, key = "Polarity", value = "Words")

# Colors for blog 
colors <- c("#E63D3D",#red 
            "#694DE6", #purple 
            "#196CFF", #blue
            "#3EA3B3", #aqua
            "#72C22B", #green
            "#4E9435",#green
            "#D4159F", #pink
            "#F59824", #orange
            "#631257", #burgundy
            "#717174") #gre

# Graph sentiment output
sentiment_graph_inst <- ggplot(sentimiento_df_inst, aes(doc_id, Words, color = Polarity, group = Polarity)) +
  geom_line(size = 1) +
  ggtitle("Sentiment Scores Gender Institutions on Twitter 
          (spanish sentiment dictionary online)") +
  scale_color_manual(values = colors) +
  theme_minimal() +
  xlab("Institutions") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

sentiment_graph_inst
```


```{r}
# Sentiment analysis with improved dictionnary including words in topic models. 

# Dictionary 
sentimiento_d_fem <- read.delim(file = "SpanishSentimentLexicon_feminist_discourse_v4.txt",
                          header = F,
                          col.names = c("word", "code", "sentiment", "score 2"))

sentimiento_dict_fem <- as.dictionary(sentimiento_d_fem)
sentimiento_dict_fem

# Dfm with dictionary by main occupation
sentimiento_dfm2 <- dfm(institutions_corp,
                       groups = c("screen_name"),
                       dictionary = sentimiento_dict_fem)

sentimiento_df2 <- convert(sentimiento_dfm2, "data.frame") %>%
  gather(neg, pos, key = "Polarity", value = "Words")

# Graph sentiment output
sentiment_graph_inst2 <- ggplot(sentimiento_df2, aes(doc_id, Words, color = Polarity, group = Polarity)) +
  geom_line(size = 1) +
  ggtitle("Sentiment Scores Gender Institutions on Twitter 
          (improved dictionary)") +
  scale_color_manual(values = colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.8)) +
  xlab("Institutions")

sentiment_graph_inst2
# Just by adding more positive words when talking about gender issues (old dictionary 456 to 504) the amount of positive words increase significantly. 
# Dictionary we added words that are in the topic model negative and positive, althought more positive. 
# Improve dictionaries
# Make sense journalists use more postive words as activists policy maker, and writers. 
```