---
title: "gather_institutional_tweets"
output: html_document
---

```{r, include = FALSE}

library(twitteR)
library(tidyverse)
library(rtweet)

# API authorization 
rtweet::create_token(app = "aletheia_hertie", 
                     consumer_key = "dUccFFYUBCdImYFvQeLVNV3ij",
                     access_secret = "g5Zpp9lmwPfdW5JB2l4srFu8Y1BGBeNvt3BkDjcUaJJrk",
                     access_token = "10536312-kRxNG26Yo9SWavI8ksHzOs1rhw9PGA90Kp5ioIelD",
                     consumer_secret = "RPLTQRvGix0sK6QKkNS0ZJq6y1lsc5nR5OGDahV77mydUYTplq")

```

```{r, echo=FALSE}

 # Chosen institutional accounts 
institutions <- c("Campaña por el Derecho al Aborto Legal en Colombia",
"Casa de la Mujer",
"Católicas por el Derecho a Decidir Colombia",
"Colombia Diversa",
"Comisión Legal para la Equidad de la Mujer",
"Comisión Nacional de Mujeres Indígenas -Colombia",
"Compromiso Diverso -  Secretaría de Integración Bogotá",
"Consejera Presidencial para la Equidad de la Mujer",
"Corporación Ensayos",
"Corporación Humanas",
"Cumbre mujeres y paz",
"Estamos Listas",
"Federación Nacimos Listas",
"Fondo Lunaria Mujer",
"Las Igualadas",
"Las Parceras",
"Librería de Mujeres",
"Liga de las Mujeres",
"Limpal Colombia",
"Mesa LGBT Bogotá",
"Mesa Nacional de Mujeres Negras/Afrocolombianas/Raizales y Palenqueras",
"Mesa Nacional de seguimiento a la Ley 1257",
"Mesa por la vida",
"Mujeres de FARC",
"ONU Mujeres Colombia",
"Red Nacional de las Mujeres",
"Ruta Pacífica de las Mujeres",
"Se Puede Ser",
"Secretaria de la Mujer Bogota",
"Secretaria de la Mujer del Partido Conservador",
"Sentiido",
"Siete Polas",
"Sisma Mujer",
"Soy Mujer Paz",
"Viejas Verdes",
"Women's Link",
"RecSisters",
"Ni con el Pétalo de Una Rosa") 

usernames <- c("@Aborto_LegalCol",
"@casa_la",
"@CDD_Colombia",
"@ColombiaDiversa",
"@ComisionMujerCo",
"@CNMIColombia",
"@SubLGBTI",
"@equidad_mujer",
"@CEnsayos",
"@HumanasColombia",
"@Cumbremujeres",
"@Estamos_Listas",
"@NacimosListas",
"@LunariaFondo",
"@LasIgualadas",
"@LasParcerasCol",
"@ElTelarLibreria",
"@LigaMujeres", 
"@LIMPALCOLOMBIA",
"@MesaLGBT", 
"@MesaMujeresAfro",
"@Mesa1257",
"@mesaporlavida",
"@MujerFariana",
"@ONUMujeresCol",
"@RNMColombia",
"@RutaPacificaM",
"@SePuedeSer",
"@secredistmujer",
"@MujeresPC",
"@Sentiido",
"@sietepolas",
"@SismaMujer",
"@SoyMujerPaz",
"@viejas_verdes",
"@womenslink",
"@RecSisters",
"@niconelpetaloof")
              
institutions <- data.frame()

for (i in usernames) {
  institutions <- rbind(institutions, 
                       twitteR::userTimeline(user = i, n = 3200, includeRts = TRUE) %>%
                         twListToDF())
  }

save(institutions, file = "data/tweets_institutions.RData")

```


```{r}

# Read list of accounts to scrape 
accounts_institutions <- read_csv("data/twitter_accounts_inst.csv")

# Gather last 3200 tweets from each account 
institutions <- rtweet::get_timeline(accounts_institutions$username, n = 3200)

# Modify institutions dataframe in order to do left_join with tweets df
accounts_institutions <- accounts_institutions %>% 
  rename(screen_name = username) %>% 
  mutate(screen_name = str_remove(screen_name, "@"))
  
# Add covariates included in initial list to tweets df 
institutions <- left_join(institutions, accounts_institutions, by = "screen_name")

save(institutions, file = "data/tweets_institutions.RData")

```