---
title: "network_analysis_2"
author: "Mariana Saldarriaga"
output: html_document
---

```{r}
# Load dataframe with all tweets from individual accounts scraped from twitter
load("data/tweets_feminists.RData")

# Create a new variable with day of publication
feminists_network <- feminists %>% 
  mutate(created_at = as_date(created_at),
         day_published = ymd(created_at)) 

# We don't group by "screen name" but we do want to trim for the last 6 months
fem_jul_nov_2020_network <- feminists_network %>% filter(day_published >= "2020-07-01") 
```

```{r}
# Calculate the number of followers of each Twitter account

# Extract the usernames from the non-anonymised dataset
users <- unique(fem_jul_nov_2020_network$screen_Name)
users <- sapply(fem_jul_nov_2020_network, as.character)

users.fem_jul_nov_2020_network <- data.frame(users = users, followers = "", stringsAsFactors = FALSE)

# Loop to populate users$followers with a follower count obtained from Twitter API
# loop to populate users$followers with a follower count obtained from Twitter API
for (i in 1:nrow(users.fem_jul_nov_2020_network)) 
{
  # tell the loop to skip a user if their account is protected 
  # or some other error occurs  
  result <- try(getUser(users.fem_jul_nov_2020_network$users[i])$followers_Count, silent = FALSE);
  if(class(result) == "try-error") next;
  # get the number of followers for each user
  users.fem_jul_nov_2020_network$followers[i] <- getUser(users.fem_jul_nov_2020_network$users[i])$followers_Count
  # tell the loop to pause for 60 s between iterations to 
  # avoid exceeding the Twitter API request limit
  # this is going to take a long time if there are a lot
  # of users, good idea to let it run overnight
  print('Sleeping for 60 seconds...')
  Sys.sleep(60); 
}

```

```{r}
# Select top retweeted tweets
table(fem_jul_nov_2020_network$retweetCount)
selected <- which(fem_jul_nov_2020_network$retweetCount >= 5)

graph_retweets <- plot(x=fem_jul_nov_2020_network$day_published,
                       y=fem_jul_nov_2020_network$retweetCount,
                       type="l",
                       col="grey",
                       xlab="Date",
                       ylab="Times retweeted")
                       
                       colors <- rainbow(10)[1:length(selected)]
points(dates[selected], tweets.df$retweetCount[selected],
pch=19, col=colors)
text(dates[selected], tweets.df$retweetCount[selected],
tweets.df$text[selected], col=colors, cex=.9)
```

