---
title: "Topic model feminists"
author: "Adelaida Barrera"
date: "12/9/2020"
output: html_document
---

```{r}
library(tidyverse)
library(stm)
library(quanteda)
library(tidytext)
library(ggthemes)
```

# Load data from sample taken in cleaning code

```{r}

load("data/sample_non_congress_topicmodel.Rdata")

```

#Running the structural topic model

```{r}

#Make the quanteda dfm a stm corpus for running the model
stm_sample_non_congress <- asSTMCorpus(sample_non_congress_topicmodel)

# Getting info from the corpus
out <- prepDocuments(stm_sample_non_congress$documents, 
                     stm_sample_non_congress$vocab, 
                     stm_sample_non_congress$meta)

# Running the structural topic model, defining 10 topics. 
model_topics_non_congress <- stm(documents = out$documents, 
              vocab = out$vocab, 
              K = 10, seed = 12345)

# Save the output for future plotting or analysis 
save(model_topics_non_congress, file = "model_topics_feminists")

```

#See what came out 

```{r}

plot(model_topics_non_congress, type = "labels", labeltype = "prob", topics = (1:3)) # or frex, lift, score
plot(model_topics_non_congress, type = "labels", labeltype = "prob", topics = (4:6)) 
plot(model_topics_non_congress, type = "labels", labeltype = "prob", topics = (7:9)) 
plot(model_topics_non_congress, type = "labels", labeltype = "prob", topics = 10)
 
```

